version: '3'

services:
  redis:
    image: redis:6
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]  # memory only
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ${PWD}/database/init.sql:/docker-entrypoint-initdb.d/00_init.sql
